Vidlly/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using Vidlly.Models;
using Vidlly.ViewModels;

namespace Vidlly.Controllers
{
    public class NotesController : Controller
    {

        private ApplicationDbContext _context;


        public NotesController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Notes
        public ActionResult Index(int? page)
        {

            var userid = User.Identity.GetUserId();

            var model = new NoteViewModel
            {
                Notes = _context.Notes
                    .Where(n => n.UserId == userid)
                    .ToList().ToPagedList(page?? 1,5)
            };

            return View(model);
        }
    }
}

Vidlly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="app_version" data-spy="scroll" data-target="#navbarApp" data-offset="98">

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Vidly", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <!-- Collection of nav links and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Customers", "Index", "Customers", null, new { @class = "nav-link" })</li> 
                    <li>@Html.ActionLink("Movies", "Index", "Movies", null, new { @class = "nav-link" })</li> 
                    <li>@Html.ActionLink("My Notes", "Index", "Notes", null, new { @class = "nav-link" })</li> 
                    <li>@Html.ActionLink("Rental", "Index", "Rental", null, new { @class = "nav-link" })</li>
                    @Html.Partial("_LoginPartial")

                </ul>
            </div>
        </div>
    </nav>

<div class="container body-content" style="margin-top: 30px">
    @RenderBody()
        
</div>
<hr />

<footer class="footer-btm text-center">
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
</footer> 

@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @RenderSection("scripts", required: false)
</body>
</html>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}